WORLD_BANK_INDICATORS = {
    # Economic Growth & Output
    'NY.GDP.MKTP.CD': 'GDP (current US$)',
    'NY.GDP.MKTP.KD.ZG': 'GDP growth (annual %)',
    'NY.GDP.MKTP.PP.CD': 'GDP, PPP (current international $)',
    'NY.GDP.PCAP.CD': 'GDP per capita (current US$)',
    'NY.GDP.PCAP.KD.ZG': 'GDP per capita growth (annual %)',
    'NE.GDI.TOTL.KD.ZG': 'Gross capital formation (annual % growth)',
    'NE.GDI.TOTL.ZS': 'Gross capital formation (% of GDP)',
    'NV.IND.TOTL.CD': 'Industry (including construction), value added (current US$)',
    'NV.IND.TOTL.KD.ZG': 'Industry (including construction), value added (annual % growth)',
    'NV.IND.TOTL.ZS': 'Industry (including construction), value added (% of GDP)',
    'SL.IND.EMPL.ZS': 'Employment in industry (% of total employment) (modeled ILO estimate)',
    'NV.SRV.TOTL.CD': 'Services, value added (current US$)',
    'NV.SRV.TOTL.KD.ZG': 'Services, value added (annual % growth)',
    'NV.SRV.TOTL.ZS': 'Services, value added (% of GDP)',
    'NY.GNP.MKTP.KD.ZG': 'GNI growth (annual %)',
    'NY.GNP.MKTP.PP.CD': 'GNI, PPP (current international $)',
    'BG.GSR.NFSV.GD.ZS': 'Trade in services (% of GDP)',
    'CM.MKT.LCAP.GD.ZS': 'Market capitalization of listed domestic companies (% of GDP)',
    'CM.MKT.TRAD.GD.ZS': 'Stocks traded, total value (% of GDP)',
    'NY.GDS.TOTL.ZS': 'Gross domestic savings (% of GDP)',
    'NY.GNS.ICTR.ZS': 'Gross savings (% of GDP)',
    'NE.TRD.GNFS.ZS': 'Trade (% of GDP)',
    # Fiscal Position & Government Finance
    'GC.DOD.TOTL.GD.ZS': 'Central government debt, total (% of GDP)',
    'DT.DOD.DIMF.CD': 'Use of IMF credit (DOD, current US$)',
    # 'GC.BAL.CASH.GD.ZS': 'Cash surplus/deficit (% of GDP)',
    'GC.REV.XGRT.GD.ZS': 'Revenue, excluding grants (% of GDP)',
    'GC.XPN.TOTL.GD.ZS': 'Expense (% of GDP)',
    # Monetary Stability
    'FP.CPI.TOTL.ZG': 'Inflation, consumer prices (annual %)',
    'NY.GDP.DEFL.KD.ZG': 'Inflation, GDP deflator (annual %)',
    'FR.INR.RINR': 'Real interest rate (%)',
    'FM.LBL.BMNY.GD.ZS': 'Broad money (% of GDP)',
    'FM.LBL.BMNY.ZG': 'Broad money growth (annual %)',
    # External Sector & BOP
    'BN.CAB.XOKA.CD': 'Current account balance (current US$)',
    'NE.IMP.GNFS.ZS': 'Imports of goods and services (% of GDP)',
    'NE.EXP.GNFS.ZS': 'Exports of goods and services (% of GDP)',
    'BN.CAB.XOKA.GD.ZS': 'Current account balance (% of GDP)',
    'GC.TAX.INTT.RV.ZS': 'Taxes on international trade (% of revenue)',
    'BM.KLT.DINV.WD.GD.ZS': 'Foreign direct investment, net outflows (% of GDP)',
    'BX.KLT.DINV.WD.GD.ZS': 'Foreign direct investment, net inflows (% of GDP)',
    'DT.DOD.PVLX.GN.ZS': 'Present value of external debt (% of GNI)',
    'DT.DOD.DECT.GN.ZS': 'External debt stocks (% of GNI)', 
    'DT.DOD.DLXF.CD': 'External debt stocks, long-term (DOD, current US$)',
    'DT.DOD.DSTC.CD': 'External debt stocks, short-term (DOD, current US$)',
    'DT.TDS.DECT.CD': 'Debt service on external debt, total (TDS, current US$)',
    'NE.RSB.GNFS.ZS': 'External balance on goods and services (% of GDP)',
    # 'DT.DOD.DECT.PC.CD': 'Total external debt per capita (US$)',
    # 'FI.RES.TOTL.DT.ZS': 'Total reserves (% of total external debt)', # Slow
    'FI.RES.TOTL.MO': 'Total reserves in months of imports',
    'NE.EXP.GNFS.CD': 'Exports of goods and services (current US$)',
    'NE.IMP.GNFS.CD': 'Imports of goods and services (current US$)',
    'TX.VAL.TECH.CD': 'High-technology exports (current US$)',
    # Debt & Credit Sustainability
    # 'DT.TDS.DECT.EX.ZS': 'Total debt service (% of exports of goods, services and primary income)', # Slow
    'DT.TDS.DECT.GN.ZS': 'Total debt service (% of GNI)',
    'DT.DOD.DSTC.IR.ZS': 'Short-term debt (% of total reserves)',
    'GC.XPN.INTP.RV.ZS': 'Interest payments (% of revenue)',
    'GC.XPN.INTP.ZS': 'Interest payments (% of expense)',
    'FR.INR.DPST': 'Deposit interest rate (%)',
    'FR.INR.LEND': 'Lending interest rate (%)',
    'NE.CON.GOVT.ZS': 'General government final consumption expenditure (% of GDP)',
    'NE.CON.PRVT.ZS': 'Households and NPISHs final consumption expenditure (% of GDP)',
    'NE.CON.TOTL.ZS': 'Final consumption expenditure (% of GDP)',
    'NE.DAB.TOTL.ZS': 'Gross national expenditure (% of GDP)',
    # 'DT.INT.DECT.GN.ZS': 'Interest payments on external debt (% of GNI)',
    # 'DT.INR.DPPG': 'Average interest on new external debt commitments (%)',
    'FS.AST.DOMO.GD.ZS': 'Bank assets to GDP (%)',
    # 'FM.AST.CGOV.GD.ZS': 'Claims on central government (% of GDP)',
    # Labor & Demographics
    'SL.UEM.1524.ZS': 'Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate)',
    'SL.UEM.INTM.ZS': 'Unemployment with intermediate education (% of total labor force with intermediate education)',
    'SL.UEM.BASC.ZS': 'Unemployment with basic education (% of total labor force with basic education)',
    'SL.UEM.TOTL.ZS': 'Unemployment, total (% of total labor force) (modeled ILO estimate)',
    'EN.URB.LCTY.UR.ZS': 'Population in the largest city (% of urban population)',
    'SP.POP.TOTL': 'Population, total',
    'SP.POP.GROW': 'Population growth (annual %)',
    'SP.URB.TOTL.IN.ZS': 'Urban population (% of total population)',
    'EN.POP.DNST': 'Population density (people per sq. km of land area)',
    'SE.PRM.CUAT.ZS': 'Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)',
    'SP.POP.DPND': 'Age dependency ratio (% of working-age population)',
    'SL.TLF.CACT.ZS': 'Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)',
    # 'SL.UEM.LTRM.ZS': 'Unemployment, long-term (% of total unemployment)',
    # Institutional Structure
    'GE.EST': 'Government Effectiveness: Estimate',
    'RQ.EST': 'Regulatory Quality: Estimate',
    'IC.BRE.BI.OS': 'B-READY: Business Insolvency: Overall Score',
    'IC.BRE.BE.OS': 'B-READY: Business Entry: Overall Score',
    'IQ.CPA.PADM.XQ': 'CPIA quality of public administration rating (1=low to 6=high)',
    'FS.AST.PRVT.GD.ZS': 'Domestic credit to private sector (% of GDP)',
    'FM.AST.PRVT.GD.ZS': 'Monetary Sector credit to private sector (% GDP)'
}